parameters:
#    nemo64_doctrine_flysystem.example.class: Nemo64\DoctrineFlysystemBundle\Example

services:
#    nemo64_doctrine_flysystem.example:
#        class: %nemo64_doctrine_flysystem.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
