parameters:
    nemo64_doctrine_flysystem.filesystem_listener.class: Nemo64\DoctrineFlysystemBundle\EventListener\FilesystemListener

services:
    nemo64_doctrine_flysystem.filesystem_listener:
        class: %nemo64_doctrine_flysystem.filesystem_listener.class%
        tags:
            - { name: doctrine.event_listener, event: unserializeFile }
            - { name: doctrine.event_listener, event: serializeFile }